config/routes.rb
Rails.application.routes.draw do
  root "alunos#index" # Define a rota principal para a ação index de "alunos".
  resources :alunos   # Cria todas as rotas RESTful para o recurso alunos.
end

app/models/aluno.rb
class Aluno < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  def index
    @alunos = Aluno.all
  end

  def new
    @aluno = Aluno.new
  end

  def create
    @aluno = Aluno.new(aluno_params)
    if @aluno.save
      redirect_to alunos_path, notice: "Aluno criado com sucesso!"
    else
      render :new
    end
  end

  def show
    @aluno = Aluno.find(params[:id])
  end

  def edit
    @aluno = Aluno.find(params[:id])
  end

  def update
    @aluno = Aluno.find(params[:id])
    if @aluno.update(aluno_params)
      redirect_to aluno_path(@aluno), notice: "Aluno atualizado com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    @aluno = Aluno.find(params[:id])
    @aluno.destroy
    redirect_to alunos_path, notice: "Aluno excluído com sucesso!"
  end

  private

  def aluno_params
    params.require(:aluno).permit(:nome, :idade, :cpf, :telefone, :email, :data_de_aniversario, :endereco, :observacao, :status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alunos/_form.html.erb
<%= form_with(model: aluno, local: true) do |form| %>
  <% if aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aluno.errors.count, "erro") %> encontrado(s):</h2>
      <ul>
        <% aluno.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :idade %>
    <%= form.number_field :idade %>
  </div>

  <div>
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :telefone %>
    <%= form.telephone_field :telefone %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :data_de_aniversario %>
    <%= form.date_field :data_de_aniversario %>
  </div>

  <div>
    <%= form.label :endereco %>
    <%= form.text_area :endereco %>
  </div>

  <div>
    <%= form.label :observacao %>
    <%= form.text_area :observacao %>
  </div>

  <div>
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<h1>Editar Aluno</h1>
<%= render 'form', aluno: @aluno %>
<%= link_to "Voltar", alunos_path %>

app/views/alunos/index.html.erb
<h1>Lista de Alunos</h1>
<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>Email</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.nome %></td>
        <td><%= aluno.idade %></td>
        <td><%= aluno.email %></td>
        <td>
          <%= link_to "Ver", aluno_path(aluno) %> |
          <%= link_to "Editar", edit_aluno_path(aluno) %> |
          <%= link_to "Excluir", aluno_path(aluno), method: :delete, data: { confirm: "Tem certeza?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Novo Aluno", new_aluno_path %>

app/views/alunos/new.html.erb
<h1>Novo Aluno</h1>
<%= render 'form', aluno: @aluno %>
<%= link_to "Voltar", alunos_path %>

app/views/alunos/show.html.erb
<h1>Detalhes do Aluno</h1>
<p><strong>Nome:</strong> <%= @aluno.nome %></p>
<p><strong>Idade:</strong> <%= @aluno.idade %></p>
<p><strong>Email:</strong> <%= @aluno.email %></p>
<p><%= link_to "Voltar", alunos_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Escola</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>